# .travis.yml for wutils

# Set environment variables. TRAVIS is always set.
#env: DB=postgres

# At the time of this writing (2014-04), Travis provides only the old
# Ubuntu 12.04 (precise pangolin), which ships with gcc 4.6, libstdc++6-4.4 and
# no clang. We want clang++3.4, because we want something modern that supports
# C++11 properly.

# See also https://github.com/travis-ci-tester/travis-test-clang-cxx-11
# See also http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11?rq=1

language: cpp
compiler:
    #- gcc
    - clang

before_install:
    - sudo apt-get -q update
    # to be sure we get add-apt-repository
    - sudo apt-get install python-software-properties
    # for g++4.8
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    # to get a more recent boost, since the 12.04 breaks with g++ 4.8
    - sudo add-apt-repository --yes  ppa:boost-latest/ppa
    # clang 3.4
    - sudo add-apt-repository --yes ppa:h-rayflood/llvm
    # Official clang repo, but broken in include file paths
    #- sudo add-apt-repository --yes "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
    #- sudo add-apt-repository --yes "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main"
    # sudo add-apt-repository --yes "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main"

    - sudo apt-get -q update
install:
    # Wt dependencies:
    - sudo apt-get install -q libboost-random1.55-dev libboost-date-time1.55-dev libboost-regex1.55-dev libboost-program-options1.55-dev libboost-signals1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev libboost-thread1.55-dev
    # WUtils dependencies:
    - sudo apt-get install -q cmake p7zip-full
    - sudo apt-get install -q clang-3.4
    - sudo apt-get install -q g++-4.8
    # HERE: VM SNAPSHOT "BASE"
    - mkdir build && cd build
    # Get all the pre-built dependencies
    - ../scripts/get-gmock.sh && ../scripts/get-wt.sh && ../scripts/get-clang++-libc++.sh

script:
    - export CXX="clang++-3.4"
    - cmake -DGMOCK_DIR=./gmock-download/install -DWT_DIR=./wt-download/install ..
    - make
    - cd test && ./test-urlrouter



